import fs from 'node:fs/promises';
import path from 'node:path';
import { loadRegistry } from '../../validator/src/index';
import { rewriteImports } from './rewrite-imports';
const root = process.cwd();
const { items, errors } = await loadRegistry(root);
if (errors.length) throw new Error(errors.join('\n'));
const featured = [
  'magnetic-button',
  'stagger-reveal',
  'spotlight-card',
  'aurora-field',
  'prompt-composer',
  'stacked-cards',
];
items.sort((a, b) => {
  const ai = featured.indexOf(a.id),
    bi = featured.indexOf(b.id);
  return (ai < 0 ? 99 : ai) - (bi < 0 ? 99 : bi) || a.title.localeCompare(b.title);
});
const publicDir = path.join(root, 'apps/web/public');
const generated = path.join(root, 'apps/web/src/generated');
await fs.mkdir(path.join(publicDir, 'r'), { recursive: true });
await fs.mkdir(generated, { recursive: true });
const names = new Set(items.map((i) => `${i.id}.json`));
for (const name of await fs.readdir(path.join(publicDir, 'r')))
  if (name.endsWith('.json') && !names.has(name)) await fs.unlink(path.join(publicDir, 'r', name));
const site = (process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000').replace(/\/$/, '');
const registryItems = [];
const sources: Record<string, { path: string; content: string }[]> = {};
for (const item of items) {
  const files = await Promise.all(
    item.files.map(async (file) => {
      let content = await fs.readFile(path.join(root, 'registry', file), 'utf8');
      if (/\.tsx?$/.test(file)) content = rewriteImports(content);
      return { path: file, content };
    }),
  );
  sources[item.id] = files;
  const artifact = {
    $schema: 'https://ui.shadcn.com/schema/registry-item.json',
    name: item.id,
    type: 'registry:component',
    title: item.title,
    description: item.description,
    author: item.author.name,
    dependencies: Object.entries(item.dependencies).map(([name, version]) => `${name}@${version}`),
    files: files.map((f) => ({
      ...f,
      type: /\.tsx?$/.test(f.path) ? 'registry:component' : 'registry:file',
      target: `components/buildwithme/${item.id}/${path.basename(f.path)}`,
    })),
    meta: {
      license: item.license,
      origin: item.origin,
      sourceUrl: item.sourceUrl,
      adaptations: item.adaptations,
      parent: item.parent,
    },
  };
  await fs.writeFile(
    path.join(publicDir, 'r', `${item.id}.json`),
    JSON.stringify(artifact, null, 2) + '\n',
  );
  registryItems.push(artifact);
}
await fs.writeFile(
  path.join(publicDir, 'registry.json'),
  JSON.stringify(
    {
      $schema: 'https://ui.shadcn.com/schema/registry.json',
      name: 'buildwithme-ui',
      homepage: site,
      items: registryItems,
    },
    null,
    2,
  ) + '\n',
);
const discovery = items.map(({ id, title, description, category, engine, tags, author }) => ({
  id,
  title,
  description,
  category,
  engine,
  tags,
  author,
}));
await fs.writeFile(
  path.join(publicDir, 'index.v1.json'),
  JSON.stringify({ schemaVersion: 1, items: discovery }, null, 2) + '\n',
);
await fs.writeFile(path.join(generated, 'registry.json'), JSON.stringify(items, null, 2) + '\n');
await fs.writeFile(path.join(generated, 'sources.json'), JSON.stringify(sources, null, 2) + '\n');
await fs.writeFile(
  path.join(generated, 'previews.ts'),
  `// Generated by registry:build. Do not edit.\nexport const previewLoaders = {\n${items.map((i) => `  '${i.id}': () => import('../../../../registry/${i.preview.replace(/\.tsx?$/, '')}'),`).join('\n')}\n};\n`,
);
console.log(
  `Generated ${items.length} installable items, discovery index, source documents and lazy preview map.`,
);
